### ISSUE TITLE
It doesn't work in private windows

### ISSUE THREAD

**Issue by izumitelj** [GChristensen/ishell#2]
Hi there! I'm wondering if this is normal behavior or just my local situation. It does open the modal window but it is blank and there are no commands available.

Windows 10 Pro
FF 102.0.1 (64-bit)
Addon is allowed in private windows

Thanks!

**Comment by GChristensen** [comment]
Unfortunately, some WebExtensions API, such as [getBackgroundPage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getBackgroundPage) is not available in private windows. This can not be helped.

**Comment by izumitelj** [comment]
That's pity, I browse mostly in private. 
Thanks for the explanation!
