### ISSUE TITLE
your commands

### ISSUE THREAD

**Issue by ledemon** [GChristensen/ishell#3]
hi, every time the addon is updated I have to unselect all the commands I dont want to use, is this a common thing or I have something wrong, also sometimes if I unselect one or few commands that invert all the actual state of the rest of the commands (after firefox restart), those that were selected are deselected and vice versa, except for the user added commands (basic direct link search commands) they keep unchanged.

**Comment by GChristensen** [comment]
>hi, every time the addon is updated I have to unselect all the commands I dont want to use, is this a common thing or I have something wrong

That was a pretty funny bug. Because of that, don't know, was it fixed, though. Fix should be available in v0.9.7.

>also sometimes if I unselect one or few commands that invert all the actual state of the rest of the commands (after firefox restart), those that were selected are deselected and vice versa, except for the user added commands

Can't reproduce this. If the fix will not help, please report.
