### ISSUE TITLE
Main ishell panel

### ISSUE THREAD

**Issue by ledemon** [GChristensen/ishell#5]
Hi, since the last updates when you use one command and press enter the main ishell panel keeps open.

**Comment by GChristensen** [comment]
Hi, what is the browser and the command?

**Comment by ledemon** [comment]
firefox all commands (You are using iShell v1.1.1 (MV2))
chrome seems to work fine (You are using iShell v1.0.4 (MV3))

**Comment by GChristensen** [comment]
Fixed. Please update to v1.1.2.

**Comment by ledemon** [comment]
as always, thank you for your work with this addon
